name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.0.1, etc.

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP package
        run: |
          zip -r jotty-clipper-${{ github.ref_name }}.zip manifest.json popup.html popup.js popup.css options.html options.js options.css background.js content.js icons/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: jotty-clipper-${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
